### ISSUE TITLE
Library doesn't work, always caught java.lang.NoClassDefFoundError: com.ulogin.sdk.R$layout

### ISSUE THREAD

**Issue by dajver** [ulogin/Android#3]
Hi, can somebody help me please, I always caught java.lang.NoClassDefFoundError: com.ulogin.sdk.R$layout after click on login button of some social network... What could be the problem?

**Comment by dajver** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ulogin/sdk/R$layout;
                                                     at com.ulogin.sdk.UloginAuthActivity.onCreate(UloginAuthActivity.java:86)
                                                     at android.app.Activity.performCreate(Activity.java:5990)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ulogin.sdk.R$layout" on path: DexPathList[[zip file "/data/app/com.edinar.crypt.app-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at com.ulogin.sdk.UloginAuthActivity.onCreate(UloginAuthActivity.java:86) 
                                                     at android.app.Activity.performCreate(Activity.java:5990) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                    Suppressed: java.lang.ClassNotFoundException: com.ulogin.sdk.R$layout
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                            ... 15 more
                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by gumam** [comment]
Is actual. same problem. How you are resolved it?

**Comment by gumam** [comment]
thk. closed
